# Generated by Django 4.2.1 on 2023-06-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
    ]
