# Generated by Django 4.2.1 on 2023-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazYflora', '0001_initial'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codID',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigoID',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False, verbose_name='codigoID'),
            preserve_default=False,
        ),
    ]
