# Generated by Django 4.2.1 on 2023-07-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazYflora', '0004_boleta_detalleboleta_delete_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleboleta',
            name='user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuario'),
        ),
    ]
