# Generated by Django 4.2.1 on 2023-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazYflora', '0007_remove_producto_user_boleta_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Username')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, verbose_name='Apellido')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('password1', models.CharField(blank=True, max_length=100, verbose_name='Password1')),
                ('password2', models.CharField(blank=True, max_length=100, verbose_name='Password2')),
            ],
        ),
    ]
